name:  timeline_charter_example
description:  A sample application

dependencies:
  timeline_charter:
    path: ../timeline_charter
  polymer: any

transformers:
- polymer:
    entry_points:
    - 'web/index.html'

